---
- name: copying index.php to webserver
  hosts: webserver
  vars:
    var1: production
  tasks:
    - template:
        src: cloud-demo/index.php.j2
        dest: /var/www/html/index.php
      changed_when: true
      notify:
        - restart httpd
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
