---
# tasks file for db

- name: mysql mariadb105 installation 
  yum:
    name: mariadb105-server
    state: present
- name: running mysql
  service:
    name: mariadb
    state: started
- name: copy sql file to home dir
  copy: 
    src: create_db_webtest.sql
    dest: /home/ansible-user
- name: creating user, db, and table
  shell: 'mysql -uroot < /home/ansible-user/create_db_webtest.sql'
  register: result
  failed_when: "'database exists' in result.stderr_lines"
- debug:
    var: result
- name: stopping firewalld
  service:
    name: firewalld
    state: stopped